version: "3.8"

services:
  postgresql:
    image: postgres:16-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_USER}
      POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./dump:/home/dump
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  internal:
    name: ${APP_NAME}-net
